services:
  - type: web
    name: flash-max
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: REVIEWS_ADMIN_KEY
        sync: false
      - key: DATA_DIR
        value: ./data
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
